Viztech/Controllers/SystemSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Viztech.Models;

namespace Viztech.Controllers
{
    public class SystemSetupController : Controller
    {
        ViztecEntities context = new ViztecEntities();
        // GET: SystemSetup
        public ActionResult Index(int S = 0)
        {
            if (Session["USER_ID"] != null)
            {
                if (DAL.CheckFunctionValidity("Users", "AddUser", Session["USER_ID"].ToString()))
                {
                    string message = "";
                    try
                    {
                        if (S != 0)
                        {
                            BIO_SYSTEM_SETUP edit = new BIO_SYSTEM_SETUP();
                            edit = context.BIO_SYSTEM_SETUP.Where(m => m.SS_ID == S).FirstOrDefault();
                            if (edit != null)
                            {
                                return View(edit);
                            }
                            else
                            {
                                message = "No data found in the system-setup.";
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        message = DAL.LogException("Users", "AddUser", Session["USER_ID"].ToString(), ex);
                    }
                    finally
                    {
                        ViewBag.message = message;
                    }
                }
                else
                {
                    return RedirectToAction("UnAuthorizedUrl", "Error");
                }
            }
            else
            {
                return RedirectToAction("UnAuthorizedUrl", "Error");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Index(BIO_SYSTEM_SETUP db_table)
        {
            if (Session["USER_ID"] != null)
            {
                if (DAL.CheckFunctionValidity("Users", "AddUser", Session["USER_ID"].ToString()))
                {
                    string message = "";
                    try
                    {
                        BIO_SYSTEM_SETUP UpdateEntity = new BIO_SYSTEM_SETUP();
                        if (db_table.SS_ID != 0)
                        {
                            UpdateEntity = context.BIO_SYSTEM_SETUP.Where(m => m.SS_ID == db_table.SS_ID).FirstOrDefault();
                            if (UpdateEntity != null)
                            {
                                UpdateEntity.SS_SESSION_TIME = db_table.SS_SESSION_TIME;
                                UpdateEntity.SS_MAKER_ID = db_table.SS_MAKER_ID;
                                UpdateEntity.SS_CHECKER_ID = db_table.SS_CHECKER_ID;
                                UpdateEntity.SS_CHECKER_DATETIME = DateTime.Now;
                                context.Entry(UpdateEntity).State = System.Data.Entity.EntityState.Modified;
                                int Rowcount = context.SaveChanges();
                                if (Rowcount > 0)
                                    message = "Application session time updated sucessfully.";
                                else
                                    message = "Error while updating the record.";
                            }
                            else
                                message = "No data found in the system-setup.";
                        }
                        else
                            message = "Select the record to continue.";

                    }
                    catch (Exception ex)
                    {
                        message = DAL.LogException("Users", "AddUser", Session["USER_ID"].ToString(), ex);
                    }
                    finally
                    {
                        ViewBag.message = message;
                    }
                   return View();
                }
                else
                {
                    return RedirectToAction("UnAuthorizedUrl", "Error");
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [ChildActionOnly]
        public PartialViewResult IndexList()
        {
            if (Session["USER_ID"] != null)
            {
                string SessionUser = Session["USER_ID"].ToString();
                List<BIO_SYSTEM_SETUP> ViewData = context.BIO_SYSTEM_SETUP.ToList();
                return PartialView(ViewData);
            }
            else
            {
                return PartialView(null);
            }
        }
    }
}

Viztech/Views/SystemSetup/Index.cshtml
@model Viztech.Models.BIO_SYSTEM_SETUP

@{
    ViewBag.Title = "System-Setup";
    ViewBag.Controller = "Home";
    ViewBag.Action = "System-Setup";

    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fas fa-times"></span></button>
            @ViewBag.message
        </div>
    }
}

@using (Html.BeginForm("Index", "SystemSetup", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.SS_ID)

    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Manage Configration</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
        </div>
        <!-- /.Case Form Start -->
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.Label("Session Time")
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SS_SESSION_TIME, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Session time in minutes" } })
                            @Html.ValidationMessageFor(model => model.SS_SESSION_TIME, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-outline-primary" />
                </div>
            </div>
        </div>
    </div>
    <div>
        @{
            Html.RenderAction("IndexList", "SystemSetup");
        }
    </div>
}

Viztech/Views/SystemSetup/IndexList.cshtml
@model IEnumerable<Viztech.Models.BIO_SYSTEM_SETUP>

@if (Model != null)
{
    if (Model.Count() > 0)
    {
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">System-Setup</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered text-center table-hover">
                    <thead class="Custom-Table-Head">
                        <tr>
                            <th>@Html.Label("Session Time")</th>
                            <th>@Html.Label("Action")</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SS_SESSION_TIME)
                                </td>
                                <td>
                                    <a href="@Url.Action("Index", "SystemSetup", new { S = item.SS_ID })" data-toggle="tooltip" title="Edit @item.SS_SESSION_TIME" class="btn btn-outline-primary">Edit</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
}